steps:
- name: gcr.io/cloud-builders/docker
  args: ['build',
        '--build-arg',
        'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}',
        '-t',
        'gcr.io/$PROJECT_ID/react2',
        '-f',
        'Dockerfile',
        '.']
images:
- gcr.io/$PROJECT_ID/react2
