# this docker-compose.yaml is non-functional at the moment...
# could use the Docker.dev file in each project app in here to orchestrate them together on macbook host
---
version: '3'
services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      PORT: ${PORT:-8080}
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
    - "3001:8080"
    environment:
      PORT: ${PORT:-8080}
    
